import Head from 'next/head';
import CardsSection from '@/components/Layout/CardsSection';
import { clients, posts, work } from '@/db/MockDB';
import { GrSend } from 'react-icons/gr';

import dynamic from 'next/dynamic';
import Hero from '@/components/Layout/HeroSection/Hero';
import InfiniteSlider from '@/components/InfiniteSlider/InfiniteSlider';
import Header from '@/components/Layout/Header/Header';

export default function Home() {
  const FooterSection = dynamic(
    () => import('../components/Layout/Footer/Footer')
  );
  return (
    <>
      <Head>
        <title>H&D Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Header />
        <main className="main-style px-4 font-bold ">
          <Hero />

          <section className=" bg-base-500 w-full rounded overflow-hidden my-4 flex flex-col gap-4 justify-around py-4 items-center lg:flex-row lg:gap-0">
            <div>Subscribe to newsletter notifications!</div>
            <div>
              <form className="flex justify-center items-center bg-neutral-50 border rounded">
                <input
                  type="email"
                  placeholder="Send us a email! "
                  className=" text-slate-900 p-2 "
                />
                <button className=" text-slate-900 p-2 text-2xl ">
                  <GrSend />
                </button>
              </form>
            </div>
          </section>

          {/* <Slide /> */}
          <InfiniteSlider />
          <section>
            <CardsSection
              content={work}
              title="Our work"
              layoutType="only_title"
            />
            <CardsSection
              content={posts}
              title="Our posts"
              layoutType="includes_text"
            />
            <CardsSection
              content={clients}
              title="Happy Costumers!"
              title_sx="bg-yellow-500 py-4"
              layoutType="includes_text_rounded"
            />
          </section>
        </main>
        <FooterSection />
      </>
    </>
  );
}
